Repository SSW-22/online-photo-gallery, pull requests merged in 2022-10, with the labels that each got.

#63 resolved #:62 pagination
  src/asset/dummy.js
  src/pages/BrowsEvents.js
  src/pages/MyEvent.js
Labels: feature

#65 resolved #64: thumbnail page btn
  src/asset/exit.png
  src/asset/footprints.png
  src/components/ArcText.js
  src/components/galleryPage/GalleryThumbnail.js
  tailwind.config.js
Labels: feature

#68 resolved #67: zoom in page
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/pages/Gallery.js
Labels: feature

#70 resolved #69: zomm in slide btn
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
Labels: feature

#72 resolved #71: add comments
  src/components/galleryPage/UserGallery.js
  src/pages/BrowsEvents.js
Labels: feature

#74 resolved #73: added gallery mode loading page
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/pages/Gallery.js
Labels: feature

#76 fixed #75: removing unnecessary variables
  src/App.js
  src/components/Dropdown.js
  src/components/crop/cropimage.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/firebase/uploadFileProgress.js
  src/pages/Editor.js
Labels: bug

#77 Update for deploying netlify
  src/App.js
  src/components/Dropdown.js
  src/components/crop/cropimage.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/firebase/uploadFileProgress.js
  src/pages/Editor.js
Labels: feature

#78 fixed #75: removing unnecessary variables
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/UserGallery.js
  src/components/header/Navbar.js
  src/firebase/addDocument.js
  src/firebase/deleteDocument.js
  src/firebase/deleteImageFile.js
  src/pages/Gallery.js
  src/pages/SignIn.js
  src/store/gallery-slice.js
Labels: bug

#79 update production branch
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/UserGallery.js
  src/components/header/Navbar.js
  src/firebase/addDocument.js
  src/firebase/deleteDocument.js
  src/firebase/deleteImageFile.js
  src/pages/Gallery.js
  src/pages/SignIn.js
  src/store/gallery-slice.js
Labels: bug

#81 fixed #80: loading issue in browse event page
  src/pages/BrowsEvents.js
Labels: bug

#82 Fixed loading issue in browse event page
  src/pages/BrowsEvents.js
Labels: bug

#85 resolved #84: landing animation
  package-lock.json
  package.json
  src/asset/landing1.jpg
  src/asset/landing2.jpg
  src/asset/landing3.jpg
  src/asset/landing4.jpg
  src/asset/landing5.jpg
  src/asset/landingmain.jpg
  src/components/LandingBg.js
  yarn.lock
Labels: feature

#87 resolved #86: zoom in/out transition
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
Labels: feature

#89 resolved #83 : added submision page
  src/components/MyEventStatus.js
  src/components/Thumbnail.js
  src/components/editPage/Submission.js
  src/components/galleryPage/GalleryThumbnail.js
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/pages/MyEvent.js
  src/store/gallery-slice.js
Labels: feature

#90 Woong feature 88 dark mode
  src/components/Thumbnail.js
  src/components/editPage/ModeSelector.js
  src/components/editPage/UploadImages.js
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/pages/BrowsEvents.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
  tailwind.config.js
Labels: feature

#92 resolved #91: added gallery mode animation
  package-lock.json
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/UserGallery.js
  src/index.css
  src/pages/Gallery.js
  yarn.lock
Labels: feature

#93 merge to production
  package-lock.json
  package.json
  src/asset/landing1.jpg
  src/asset/landing2.jpg
  src/asset/landing3.jpg
  src/asset/landing4.jpg
  src/asset/landing5.jpg
  src/asset/landingmain.jpg
  src/components/LandingBg.js
  src/components/MyEventStatus.js
  src/components/Thumbnail.js
  src/components/editPage/ModeSelector.js
  src/components/editPage/Submission.js
  src/components/editPage/UploadImages.js
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryThumbnail.js
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/index.css
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/pages/MyEvent.js
  src/store/gallery-slice.js
  tailwind.config.js
  yarn.lock
Labels: feature

#96 fixed #95: fixed hover effect
  src/components/Thumbnail.js
Labels: bug

#98 fixed #97: img replace
  src/asset/pencil.png
  src/components/MyEventStatus.js
Labels: bug

#100 fixed #99: all typo fixed
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/components/header/Navbar.js
Labels: bug

#102 fixed #101: space fixed
  src/components/editPage/ModeSelector.js
  src/components/editPage/UploadImages.js
Labels: bug

#104 fixed #103: horizontal wheel scroll action
  src/pages/Gallery.js
Labels: bug

#106 fixed #105: thumbnail updated after save draft on page 1
  src/firebase/checkUserGallery.js
  src/pages/Editor.js
Labels: bug

#108 fixed #107: random color always get value
  src/components/editPage/UploadThumbnail.js
Labels: bug

#110 fixed #109: prev mode
  src/components/editPage/PreviewSlide.js
  src/store/gallery-slice.js
Labels: bug

#112 fixed #111: editor btn fixed
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/pages/Editor.js
Labels: bug

#115 resolved #94: gallery mode preview button and functionality
  src/App.js
  src/components/Thumbnail.js
  src/components/editPage/UploadImages.js
  src/components/header/Navbar.js
  src/components/modal/Modal.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/index.js
  src/store/nav-slice.js
Labels: feature

#116 merge to production
  src/App.js
  src/asset/pencil.png
  src/components/MyEventStatus.js
  src/components/Thumbnail.js
  src/components/editPage/ModeSelector.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/components/header/Navbar.js
  src/components/modal/Modal.js
  src/firebase/checkUserGallery.js
  src/hooks/use-number.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/pages/MyEvent.js
  src/store/gallery-slice.js
  src/store/index.js
  src/store/modalSlice.js
  src/store/nav-slice.js
Labels: feature

#118 fixed #117 : Adjusted preview slide image width and height. Also added add-new-pic bu…
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
Labels: bug

#121 fixed #120: delete modal
  src/components/MyEventStatus.js
  src/components/modal/Modal.js
  src/pages/Editor.js
  src/pages/MyEvent.js
  src/store/modalSlice.js
Labels: bug

#123 fixed #119: preview image select error
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/pages/Editor.js
Labels: bug

#125 Merge from main
  README.md
  src/components/MyEventStatus.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/modal/Modal.js
  src/pages/Editor.js
  src/pages/MyEvent.js
  src/store/modalSlice.js
Labels: documentation, feature

#126 fixed #122: close modal when click empty space
  src/components/modal/Modal.js
  src/pages/Editor.js
Labels: bug

#127 fixed #124 : upload image limitation issue
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
Labels: bug

#129 Seungmin bug 128 dropzone disable issue
  src/components/editPage/UploadImages.js
Labels: bug

#131 resolved bug #130: browse events hover effect issue
  src/components/Thumbnail.js
Labels: bug

#132 merge to production
  src/components/Thumbnail.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/modal/Modal.js
  src/pages/Editor.js
Labels: feature

#134 fixed #133: editor mode preview slide scroll issue
  src/components/editPage/PreviewSlide.js
Labels: bug

#136 fixed #135: editor mode page issues
  netlify.toml
  src/components/editPage/PreviewSlide.js
  src/components/editPage/Submission.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/pages/Editor.js
  src/store/gallery-slice.js
Labels: bug

#138 fixed #137: editor-mode-modal-and-error-handling
  src/components/MyEventStatus.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/Submission.js
  src/components/editPage/UploadImages.js
  src/components/galleryPage/GalleryThumbnail.js
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/UserGallery.js
  src/components/modal/ConfirmationModal.js
  src/components/modal/Modal.js
  src/hooks/useBlocker.js
  src/hooks/useCallbackPrompt.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug

#139 merge to production
  netlify.toml
  src/components/MyEventStatus.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/Submission.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/components/galleryPage/GalleryThumbnail.js
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/UserGallery.js
  src/components/modal/ConfirmationModal.js
  src/components/modal/Modal.js
  src/hooks/useBlocker.js
  src/hooks/useCallbackPrompt.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug
