Repository SSW-22/online-photo-gallery, pull requests merged in 2022-11, with the labels that each got.

#141 fixed #140: landing page issues
  src/App.js
  src/asset/door.jpg
  src/asset/dummy.js
  src/asset/landing1.jpg
  src/components/LandingBg.js
  src/store/gallery-slice.js
Labels: bug

#142 Merge to production
  src/App.js
  src/asset/door.jpg
  src/asset/dummy.js
  src/asset/landing1.jpg
  src/components/LandingBg.js
  src/store/gallery-slice.js
Labels: bug

#144 fixed #143: browse event page issue
  src/components/Thumbnail.js
  src/pages/BrowsEvents.js
Labels: bug

#146 Merge to production
  src/components/Thumbnail.js
  src/pages/BrowsEvents.js
Labels: bug

#147 fixed bug #145: browse event page re-design
  src/App.js
  src/components/Thumbnail.js
  src/components/editPage/UploadThumbnail.js
  src/pages/BrowsEvents.js
  src/pages/Editor.js
Labels: bug

#150 fixed #149: nav bar issue
  src/components/Thumbnail.js
  src/components/header/Navbar.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/nav-slice.js
Labels: bug

#151 Merge to production
  src/components/Thumbnail.js
  src/components/header/Navbar.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/nav-slice.js
Labels: bug

#153 fixed #152: add media
  src/App.js
  src/components/Mobile.js
  src/hooks/useMedia.js
Labels: bug

#155 fixed #154: landing page fix
  src/App.js
  src/components/LandingBg.js
  src/pages/SignIn.js
  src/store/gallery-slice.js
Labels: bug

#157 fixed bug #156: browse envet page placeholder boxes issue
  src/pages/BrowsEvents.js
Labels: bug

#158 merget to production
  src/App.js
  src/components/LandingBg.js
  src/components/Mobile.js
  src/hooks/useMedia.js
  src/pages/BrowsEvents.js
  src/pages/SignIn.js
  src/store/gallery-slice.js
Labels: bug

#160 fixed #159: loading page add
  src/asset/loading.svg
  src/components/Loading.js
  src/pages/BrowsEvents.js
Labels: bug

#161 Merge to production
  src/asset/loading.svg
  src/components/Loading.js
  src/pages/BrowsEvents.js
Labels: bug

#164 fixed #163: lioght mode as default
  src/store/gallery-slice.js
Labels: bug

#166 Woong bug 165 css
  src/components/Dropdown.js
  src/components/Zoom.js
  src/components/editPage/ModeSelector.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/Submission.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
Labels: bug

#168 fixed #167: icon replace
  src/components/MyEventStatus.js
  src/components/editPage/ModeSelector.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/modal/Modal.js
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
Labels: bug

#170 Seungmin bug 162 modal issues
  src/components/MyEventStatus.js
  src/components/Thumbnail.js
  src/components/editPage/UploadThumbnail.js
  src/components/galleryPage/GalleryThumbnail.js
  src/components/galleryPage/UserGallery.js
  src/components/header/Navbar.js
  src/components/modal/modal-messages.js
  src/firebase/uploadFileProgress.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug

#171 Woong bug 169 modal
  src/components/editPage/ModeSelector.js
  src/components/modal/Modal.js
  src/pages/Editor.js
Labels: bug

#173 hotfix: browse page subtitle missing fixed
  src/pages/BrowsEvents.js
Labels: bug

#175 fixed #174: modal message and landing page key
  src/components/LandingBg.js
  src/pages/Editor.js
Labels: bug

#176 mode selector bug fix
  src/components/editPage/ModeSelector.js
  src/components/editPage/PreviewSlide.js
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug

#178 fixed #177: name fix
  src/components/editPage/ModeSelector.js
  src/components/editPage/PreviewSlide.js
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug

#180 fixed bug #179: nav issue
  src/components/Thumbnail.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/header/Navbar.js
  src/index.css
  src/pages/Gallery.js
Labels: bug

#182 fixed bug #181: css style issue
  src/components/Thumbnail.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/components/header/Navbar.js
  src/pages/BrowsEvents.js
  src/pages/Editor.js
Labels: bug

#183 Merge to production
  src/components/LandingBg.js
  src/components/Thumbnail.js
  src/components/editPage/ModeSelector.js
  src/components/editPage/PreviewSlide.js
  src/components/editPage/UploadImages.js
  src/components/editPage/UploadThumbnail.js
  src/components/galleryPage/GalleryLoading.js
  src/components/galleryPage/GalleryZoomedIn.js
  src/components/galleryPage/UserGallery.js
  src/components/header/Navbar.js
  src/index.css
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
  src/store/gallery-slice.js
Labels: bug

#185 fixed #184: animation
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
Labels: bug

#186 Merge to production
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
Labels: bug

#187 hotfix: edit mode preview slide issue and browse page maxpage issue f…
  src/components/editPage/PreviewSlide.js
  src/pages/BrowsEvents.js
Labels: bug

#189 fixed #188: media css and arrow position
  src/App.js
  src/components/Mobile.js
  src/components/editPage/UploadImages.js
  src/pages/Editor.js
  src/pages/Gallery.js
Labels: bug

#190 hotfix: css adjusted and readme
  README.md
  src/App.js
  src/components/Mobile.js
  src/components/Thumbnail.js
  src/components/editPage/UploadImages.js
  src/components/galleryPage/GalleryZoomedImage.js
  src/components/galleryPage/UserGallery.js
  src/pages/BrowsEvents.js
  src/pages/Editor.js
  src/pages/Gallery.js
Labels: bug, documentation

#192 fixed #191: no overflow
  src/components/Mobile.js
Labels: bug

#194 resolved #193: about and contact page
  src/App.js
  src/components/Footer.js
  src/components/LandingBg.js
  src/pages/Contact.js
  src/pages/Landing.js
  src/pages/Libraries.js
Labels: feature

#195 update footer
  src/App.js
  src/components/Footer.js
  src/components/LandingBg.js
  src/components/Mobile.js
  src/pages/Contact.js
  src/pages/Landing.js
  src/pages/Libraries.js
Labels: bug

#197 fixed #196: landing animation fix
  .vscode/launch.json
  src/App.js
  src/components/landing/LandingBg.js
  src/components/landing/LandingHeader.js
  src/pages/Landing.js
Labels: bug

#198 Merge to production
  .vscode/launch.json
  README.md
  src/App.js
  src/components/landing/LandingBg.js
  src/components/landing/LandingHeader.js
  src/pages/Landing.js
Labels: feature
